# EXAMPLE config file for snake-combine-rnaseq

reference:
/share/dennislab/databases/data/vandeLeemput_CORTECON2014_RNAseq/hg38.noalt.fa.gz

input_dir:
/share/dennislab/databases/data/vandeLeemput_CORTECON2014_RNAseq/input/

end: single


tx2gene:
/share/dennislab/databases/data/vandeLeemput_CORTECON2014_RNAseq/tx2gene_gencode_v32.tsv

transcriptome:
/share/dennislab/databases/data/vandeLeemput_CORTECON2014_RNAseq/gencode.v32.custom.rename.fa.gz

samples: RNASEQsamples.txt
